<a href="https://colab.research.google.com/github/Samir4125/pai/blob/main/lab-3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
import numpy as np

a=np.array([10,20,30])
print(type(a))
b=np.array((10,20,30))
print(type(b))
c=np.array([[10,20,30],[40,50,60]])

#ndim
print("a.ndin",a.ndim)
print("c.ndin",c.ndim)

#shape
x=np.array([1,2,3,4,5],dtype="int32")
y=np.array([
    [1,2,3],
    [4,5,6]
])
z=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

print("x.shape",x.shape)
print("y.shape",y.shape)
print("z.shape",z.shape)

#size
print("x.size",x.size)
print("y.size",y.size)
print("z.size",z.size)

#dtype
print("x.dtype",x.dtype)
print("y.dtype",y.dtype)
print("z.dtype",z.dtype)

print("x",x)

#itemsize

print("x.itemsize",x.itemsize)
print("y.itemsize",y.itemsize)

#nbytes
print("x.nbytes",x.nbytes)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
a.ndin 1
c.ndin 2
x.shape (5,)
y.shape (2, 3)
z.shape (2, 2, 3)
x.size 5
y.size 6
z.size 12
x.dtype int32
y.dtype int64
z.dtype int64
x [1 2 3 4 5]
x.itemsize 4
y.itemsize 8
x.nbytes 20


In [31]:
#indexing and slicing

a=np.array([10,20,30,40,50])

#indexing
print("a[0] :",a[0])
print("a[-1] :",a[-1])

#slicing
#array[start:stop:step]
print("a[0] :",a[0])
print("a[-1] :",a[-1])
print("a[1] :",a[1])
print("a[1:3] :",a[1:3])
print("a[-3:-1:2] :",a[-3:-1:2])
print("a[::-1] :",a[::-1])


#indexing and slicing in 2D array
b=np.array([ [1,2,3],
             [4,5,6],
             [7,8,9] ])
print("b[0,0] :",b[0,0])
print("b[0,1] :",b[0,1])
print("b[1,2] :",b[1,2])
print("b[1] :",b[1])
print("b[-1] :",b[-1])

#slicing

print("b[0:2,0:2] :",b[0:2,0:2])


#indexing + slicing
print("b[1,0:2] :",b[1,0:2])
print("b[0:2,:] :",b[0:2,:])

a[0] : 10
a[-1] : 50
a[0] : 10
a[-1] : 50
a[1] : 20
a[1:3] : [20 30]
a[-3:-1:2] : [30]
a[::-1] : [50 40 30 20 10]
b[0,0] : 1
b[0,1] : 2
b[1,2] : 6
b[1] : [4 5 6]
b[-1] : [7 8 9]
b[0:2,0:2] : [[1 2]
 [4 5]]
b[1,0:2] : [4 5]
b[0:2,:] : [[1 2 3]
 [4 5 6]]


In [38]:
#fancy indexing
a=np.array([10,20,30,40,50])
indices=[0,2,4]
b=a[indices]
print("b",b)


#boolean masking
mask=(a>30) & (a<50)
print("mask :",mask)
c=a[mask]
print("c",c)

b [10 30 50]
mask : [False False False  True False]
c [40]


In [54]:
#functions
#zeros
a=np.zeros((2,3),dtype="i")
print("a",a)
b=np.zeros((10,),dtype="i")
print("b",b)

#ones
c=np.ones((2,3),dtype="i")
print("c",c)
d=np.ones((10,),dtype="i")
print("d",d)

#arange
e=np.arange(1,10,2)
print("e",e)

#linespace
f=np.linspace(1,10,3)
print("f",f)

a [[0 0 0]
 [0 0 0]]
b [0 0 0 0 0 0 0 0 0 0]
c [[1 1 1]
 [1 1 1]]
d [1 1 1 1 1 1 1 1 1 1]
e [1 3 5 7 9]
f [ 1.   5.5 10. ]


In [60]:
#copy
a=np.array([1,2,3])
b=a[0:3].copy()
print("b",b)
b[0]=5
print("b",b)
print("a",a)

b [1 2 3]
b [5 2 3]
a [1 2 3]
